component_depth: 8

languages:
  - name: cpp
    
    production:
      include:
        - /src/.*\.cpp
        - /include/.*\.h
      exclude:
        - /tests/.*

    test:
      include:
        - /tests/.*\.cpp
